substitutions:
  _REGION: us-east1
  _REPOSITORY: movies101

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/movies101-api:$COMMIT_SHA
      - ./films

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/movies101-api:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - movies101-api
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/movies101-api:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/movies101-api:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
